--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KienMCVN/PlayerTrade
build-by-default: true
branches:
- main
projects:
 PlayerTrade:
  path: ''
  libs:
   - src: muqsit/invmenu/InvMenu
     version: ^4.6.4
...
