name: PlayerTrade
main: KienDev\Trade\Main
api: 5.13.0
version: 1.0.0
author:
- KienDev
description: This Plugin Allows Players To Trade Item With Each Other
virions: ["InvMenu"]
permissions:
  playertrade.command:
    default: true
